### ISSUE TITLE
GET epoch last parameter on private node throws an error on v2.2.0

### ISSUE THREAD

**Issue by studiowebux** [blockfrost/blockfrost-backend-ryo#205]
Hello, 

I did not do any digging or anything, but downgrading to version 2.1.0 fixed my issue, 
just dropping the error here in case it isn't caused by my setup.

```
blockfrost-ryi  | 03:46:13 3|server   | 2024-09-23T03:46:13: Error in /epochs/latest/parameters. Error: Release called on client which has already been released to the pool.
blockfrost-ryi  | 03:46:13 3|server   |     at throwOnDoubleRelease (/nix/store/kxmmrfyg4pp8kslwjy8vrfryd7d08csh-blockfrost-backend-ryo/libexec/source/node_modules/pg-pool/index.js:27:9)
blockfrost-ryi  | 03:46:13 3|server   |     at Client.release (/nix/store/kxmmrfyg4pp8kslwjy8vrfryd7d08csh-blockfrost-backend-ryo/libexec/source/node_modules/pg-pool/index.js:323:9)
blockfrost-ryi  | 03:46:13 3|server   |     at Object.handler (file:///nix/store/kxmmrfyg4pp8kslwjy8vrfryd7d08csh-blockfrost-backend-ryo/libexec/source/dist/routes/epochs/latest/parameters.js:27:34)
blockfrost-ryi  | 03:46:13 3|server   |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
blockfrost-ryi  | 03:46:13 3|server   | 2024-09-23T03:46:13: Error in /epochs/latest/parameters. Error: Release called on client which has already been released to the pool.
blockfrost-ryi  | 03:46:13 3|server   |     at throwOnDoubleRelease (/nix/store/kxmmrfyg4pp8kslwjy8vrfryd7d08csh-blockfrost-backend-ryo/libexec/source/node_modules/pg-pool/index.js:27:9)
blockfrost-ryi  | 03:46:13 3|server   |     at Client.release (/nix/store/kxmmrfyg4pp8kslwjy8vrfryd7d08csh-blockfrost-backend-ryo/libexec/source/node_modules/pg-pool/index.js:323:9)
blockfrost-ryi  | 03:46:13 3|server   |     at Object.handler (file:///nix/store/kxmmrfyg4pp8kslwjy8vrfryd7d08csh-blockfrost-backend-ryo/libexec/source/dist/routes/epochs/latest/parameters.js:27:34)
blockfrost-ryi  | 03:46:13 3|server   |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
blockfrost-ryi  | 03:46:13 3|server   | 2024-09-23T03:46:13: Error in /epochs/latest/parameters. Error: Release called on client which has already been released to the pool.
blockfrost-ryi  | 03:46:13 3|server   |     at throwOnDoubleRelease (/nix/store/kxmmrfyg4pp8kslwjy8vrfryd7d08csh-blockfrost-backend-ryo/libexec/source/node_modules/pg-pool/index.js:27:9)
blockfrost-ryi  | 03:46:13 3|server   |     at Client.release (/nix/store/kxmmrfyg4pp8kslwjy8vrfryd7d08csh-blockfrost-backend-ryo/libexec/source/node_modules/pg-pool/index.js:323:9)
blockfrost-ryi  | 03:46:13 3|server   |     at Object.handler (file:///nix/store/kxmmrfyg4pp8kslwjy8vrfryd7d08csh-blockfrost-backend-ryo/libexec/source/dist/routes/epochs/latest/parameters.js:27:34)
blockfrost-ryi  | 03:46:13 3|server   |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
blockfrost-ryi  | 03:46:57 4|server   | 2024-09-23T03:46:57: Error in /epochs/latest/parameters. Error: Release called on client which has already been released to the pool.
blockfrost-ryi  | 03:46:57 4|server   |     at throwOnDoubleRelease (/nix/store/kxmmrfyg4pp8kslwjy8vrfryd7d08csh-blockfrost-backend-ryo/libexec/source/node_modules/pg-pool/index.js:27:9)
blockfrost-ryi  | 03:46:57 4|server   |     at Client.release (/nix/store/kxmmrfyg4pp8kslwjy8vrfryd7d08csh-blockfrost-backend-ryo/libexec/source/node_modules/pg-pool/index.js:323:9)
blockfrost-ryi  | 03:46:57 4|server   |     at Object.handler (file:///nix/store/kxmmrfyg4pp8kslwjy8vrfryd7d08csh-blockfrost-backend-ryo/libexec/source/dist/routes/epochs/latest/parameters.js:27:34)
blockfrost-ryi  | 03:46:57 4|server   |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
blockfrost-ryi  | 03:47:18 4|server   | 2024-09-23T03:47:18: Error in /epochs/latest/parameters. Error: Release called on client which has already been released to the pool.
blockfrost-ryi  | 03:47:18 4|server   |     at throwOnDoubleRelease (/nix/store/kxmmrfyg4pp8kslwjy8vrfryd7d08csh-blockfrost-backend-ryo/libexec/source/node_modules/pg-pool/index.js:27:9)
blockfrost-ryi  | 03:47:18 4|server   |     at Client.release (/nix/store/kxmmrfyg4pp8kslwjy8vrfryd7d08csh-blockfrost-backend-ryo/libexec/source/node_modules/pg-pool/index.js:323:9)
blockfrost-ryi  | 03:47:18 4|server   |     at Object.handler (file:///nix/store/kxmmrfyg4pp8kslwjy8vrfryd7d08csh-blockfrost-backend-ryo/libexec/source/dist/routes/epochs/latest/parameters.js:27:34)
blockfrost-ryi  | 03:47:18 4|server   |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

I am using the Docker.

I am using a custom NAMI fork to work with the private cardano cluster. and NAMI is calling `/epochs/latest/parameters` resulted in the error above (can replicate in the browser by accessing the url) and when using 2.1.0 it works as expected.

My setup: 
I put my setup to run a local private cluster: https://github.com/studiowebux/cardano-private-node/tree/main (this is where I run blockfrost RYO so this is a private config)
The NAMI fork: https://github.com/studiowebux/nami (probably irrelevant for this issue)

Thank you.

**Comment by studiowebux** [comment]
Hello !

I updated my repo to use the latest Cardano 9.2.1.

I still observe the issue on v2.2.3 and v2.2.2 

and Rollback to 2.1.0 still works, I mean `http://localhost:3010/epochs/latest/parameters`, returns something and NAMI wallet is happy with the output.

I think it is related to : https://github.com/blockfrost/blockfrost-backend-ryo/issues/72

Do you know what could have changed between 2.1.0 and >2.x.y, that can cause the issue ?

<details>
<summary>Output using 2.1.0</summary>

```json
{
  "epoch": 382,
  "min_fee_a": 44,
  "min_fee_b": 155381,
  "max_block_size": 65536,
  "max_tx_size": 16384,
  "max_block_header_size": 1100,
  "key_deposit": "0",
  "pool_deposit": "0",
  "e_max": 18,
  "n_opt": 100,
  "a0": 0,
  "rho": 0.1,
  "tau": 0.1,
  "decentralisation_param": 0,
  "extra_entropy": null,
  "protocol_major_ver": 7,
  "protocol_minor_ver": 0,
  "min_utxo": "4310",
  "min_pool_cost": "0",
  "nonce": "e9a992cd16ae9f4e6aea50458cc1a50a1d34d70775e15ac717cf2d5931cfa4de",
  "cost_models": {
    "PlutusV1": {
      "addInteger-cpu-arguments-intercept": 197209,
      "addInteger-cpu-arguments-slope": 0,
      "addInteger-memory-arguments-intercept": 1,
      "addInteger-memory-arguments-slope": 1,
      "appendByteString-cpu-arguments-intercept": 396231,
      "appendByteString-cpu-arguments-slope": 621,
      "appendByteString-memory-arguments-intercept": 0,
      "appendByteString-memory-arguments-slope": 1,
      "appendString-cpu-arguments-intercept": 150000,
      "appendString-cpu-arguments-slope": 1000,
      "appendString-memory-arguments-intercept": 0,
      "appendString-memory-arguments-slope": 1,
      "bData-cpu-arguments": 150000,
      "bData-memory-arguments": 32,
      "blake2b_256-cpu-arguments-intercept": 2477736,
      "blake2b_256-cpu-arguments-slope": 29175,
      "blake2b_256-memory-arguments": 4,
      "cekApplyCost-exBudgetCPU": 29773,
      "cekApplyCost-exBudgetMemory": 100,
      "cekBuiltinCost-exBudgetCPU": 29773,
      "cekBuiltinCost-exBudgetMemory": 100,
      "cekConstCost-exBudgetCPU": 29773,
      "cekConstCost-exBudgetMemory": 100,
      "cekDelayCost-exBudgetCPU": 29773,
      "cekDelayCost-exBudgetMemory": 100,
      "cekForceCost-exBudgetCPU": 29773,
      "cekForceCost-exBudgetMemory": 100,
      "cekLamCost-exBudgetCPU": 29773,
      "cekLamCost-exBudgetMemory": 100,
      "cekStartupCost-exBudgetCPU": 100,
      "cekStartupCost-exBudgetMemory": 100,
      "cekVarCost-exBudgetCPU": 29773,
      "cekVarCost-exBudgetMemory": 100,
      "chooseData-cpu-arguments": 150000,
      "chooseData-memory-arguments": 32,
      "chooseList-cpu-arguments": 150000,
      "chooseList-memory-arguments": 32,
      "chooseUnit-cpu-arguments": 150000,
      "chooseUnit-memory-arguments": 32,
      "consByteString-cpu-arguments-intercept": 150000,
      "consByteString-cpu-arguments-slope": 1000,
      "consByteString-memory-arguments-intercept": 0,
      "consByteString-memory-arguments-slope": 1,
      "constrData-cpu-arguments": 150000,
      "constrData-memory-arguments": 32,
      "decodeUtf8-cpu-arguments-intercept": 150000,
      "decodeUtf8-cpu-arguments-slope": 1000,
      "decodeUtf8-memory-arguments-intercept": 0,
      "decodeUtf8-memory-arguments-slope": 8,
      "divideInteger-cpu-arguments-constant": 148000,
      "divideInteger-cpu-arguments-model-arguments-intercept": 425507,
      "divideInteger-cpu-arguments-model-arguments-slope": 118,
      "divideInteger-memory-arguments-intercept": 0,
      "divideInteger-memory-arguments-minimum": 1,
      "divideInteger-memory-arguments-slope": 1,
      "encodeUtf8-cpu-arguments-intercept": 150000,
      "encodeUtf8-cpu-arguments-slope": 1000,
      "encodeUtf8-memory-arguments-intercept": 0,
      "encodeUtf8-memory-arguments-slope": 8,
      "equalsByteString-cpu-arguments-constant": 150000,
      "equalsByteString-cpu-arguments-intercept": 112536,
      "equalsByteString-cpu-arguments-slope": 247,
      "equalsByteString-memory-arguments": 1,
      "equalsData-cpu-arguments-intercept": 150000,
      "equalsData-cpu-arguments-slope": 10000,
      "equalsData-memory-arguments": 1,
      "equalsInteger-cpu-arguments-intercept": 136542,
      "equalsInteger-cpu-arguments-slope": 1326,
      "equalsInteger-memory-arguments": 1,
      "equalsString-cpu-arguments-constant": 1000,
      "equalsString-cpu-arguments-intercept": 150000,
      "equalsString-cpu-arguments-slope": 1000,
      "equalsString-memory-arguments": 1,
      "fstPair-cpu-arguments": 150000,
      "fstPair-memory-arguments": 32,
      "headList-cpu-arguments": 150000,
      "headList-memory-arguments": 32,
      "iData-cpu-arguments": 150000,
      "iData-memory-arguments": 32,
      "ifThenElse-cpu-arguments": 1,
      "ifThenElse-memory-arguments": 1,
      "indexByteString-cpu-arguments": 150000,
      "indexByteString-memory-arguments": 1,
      "lengthOfByteString-cpu-arguments": 150000,
      "lengthOfByteString-memory-arguments": 4,
      "lessThanByteString-cpu-arguments-intercept": 103599,
      "lessThanByteString-cpu-arguments-slope": 248,
      "lessThanByteString-memory-arguments": 1,
      "lessThanEqualsByteString-cpu-arguments-intercept": 103599,
      "lessThanEqualsByteString-cpu-arguments-slope": 248,
      "lessThanEqualsByteString-memory-arguments": 1,
      "lessThanEqualsInteger-cpu-arguments-intercept": 145276,
      "lessThanEqualsInteger-cpu-arguments-slope": 1366,
      "lessThanEqualsInteger-memory-arguments": 1,
      "lessThanInteger-cpu-arguments-intercept": 179690,
      "lessThanInteger-cpu-arguments-slope": 497,
      "lessThanInteger-memory-arguments": 1,
      "listData-cpu-arguments": 150000,
      "listData-memory-arguments": 32,
      "mapData-cpu-arguments": 150000,
      "mapData-memory-arguments": 32,
      "mkCons-cpu-arguments": 150000,
      "mkCons-memory-arguments": 32,
      "mkNilData-cpu-arguments": 150000,
      "mkNilData-memory-arguments": 32,
      "mkNilPairData-cpu-arguments": 150000,
      "mkNilPairData-memory-arguments": 32,
      "mkPairData-cpu-arguments": 150000,
      "mkPairData-memory-arguments": 32,
      "modInteger-cpu-arguments-constant": 148000,
      "modInteger-cpu-arguments-model-arguments-intercept": 425507,
      "modInteger-cpu-arguments-model-arguments-slope": 118,
      "modInteger-memory-arguments-intercept": 0,
      "modInteger-memory-arguments-minimum": 1,
      "modInteger-memory-arguments-slope": 1,
      "multiplyInteger-cpu-arguments-intercept": 61516,
      "multiplyInteger-cpu-arguments-slope": 11218,
      "multiplyInteger-memory-arguments-intercept": 0,
      "multiplyInteger-memory-arguments-slope": 1,
      "nullList-cpu-arguments": 150000,
      "nullList-memory-arguments": 32,
      "quotientInteger-cpu-arguments-constant": 148000,
      "quotientInteger-cpu-arguments-model-arguments-intercept": 425507,
      "quotientInteger-cpu-arguments-model-arguments-slope": 118,
      "quotientInteger-memory-arguments-intercept": 0,
      "quotientInteger-memory-arguments-minimum": 1,
      "quotientInteger-memory-arguments-slope": 1,
      "remainderInteger-cpu-arguments-constant": 148000,
      "remainderInteger-cpu-arguments-model-arguments-intercept": 425507,
      "remainderInteger-cpu-arguments-model-arguments-slope": 118,
      "remainderInteger-memory-arguments-intercept": 0,
      "remainderInteger-memory-arguments-minimum": 1,
      "remainderInteger-memory-arguments-slope": 1,
      "sha2_256-cpu-arguments-intercept": 2477736,
      "sha2_256-cpu-arguments-slope": 29175,
      "sha2_256-memory-arguments": 4,
      "sha3_256-cpu-arguments-intercept": 0,
      "sha3_256-cpu-arguments-slope": 82363,
      "sha3_256-memory-arguments": 4,
      "sliceByteString-cpu-arguments-intercept": 150000,
      "sliceByteString-cpu-arguments-slope": 5000,
      "sliceByteString-memory-arguments-intercept": 0,
      "sliceByteString-memory-arguments-slope": 1,
      "sndPair-cpu-arguments": 150000,
      "sndPair-memory-arguments": 32,
      "subtractInteger-cpu-arguments-intercept": 197209,
      "subtractInteger-cpu-arguments-slope": 0,
      "subtractInteger-memory-arguments-intercept": 1,
      "subtractInteger-memory-arguments-slope": 1,
      "tailList-cpu-arguments": 150000,
      "tailList-memory-arguments": 32,
      "trace-cpu-arguments": 150000,
      "trace-memory-arguments": 32,
      "unBData-cpu-arguments": 150000,
      "unBData-memory-arguments": 32,
      "unConstrData-cpu-arguments": 150000,
      "unConstrData-memory-arguments": 32,
      "unIData-cpu-arguments": 150000,
      "unIData-memory-arguments": 32,
      "unListData-cpu-arguments": 150000,
      "unListData-memory-arguments": 32,
      "unMapData-cpu-arguments": 150000,
      "unMapData-memory-arguments": 32,
      "verifyEd25519Signature-cpu-arguments-intercept": 3345831,
      "verifyEd25519Signature-cpu-arguments-slope": 1,
      "verifyEd25519Signature-memory-arguments": 1
    },
    "PlutusV2": {
      "addInteger-cpu-arguments-intercept": 205665,
      "addInteger-cpu-arguments-slope": 812,
      "addInteger-memory-arguments-intercept": 1,
      "addInteger-memory-arguments-slope": 1,
      "appendByteString-cpu-arguments-intercept": 1000,
      "appendByteString-cpu-arguments-slope": 571,
      "appendByteString-memory-arguments-intercept": 0,
      "appendByteString-memory-arguments-slope": 1,
      "appendString-cpu-arguments-intercept": 1000,
      "appendString-cpu-arguments-slope": 24177,
      "appendString-memory-arguments-intercept": 4,
      "appendString-memory-arguments-slope": 1,
      "bData-cpu-arguments": 1000,
      "bData-memory-arguments": 32,
      "blake2b_256-cpu-arguments-intercept": 117366,
      "blake2b_256-cpu-arguments-slope": 10475,
      "blake2b_256-memory-arguments": 4,
      "cekApplyCost-exBudgetCPU": 23000,
      "cekApplyCost-exBudgetMemory": 100,
      "cekBuiltinCost-exBudgetCPU": 23000,
      "cekBuiltinCost-exBudgetMemory": 100,
      "cekConstCost-exBudgetCPU": 23000,
      "cekConstCost-exBudgetMemory": 100,
      "cekDelayCost-exBudgetCPU": 23000,
      "cekDelayCost-exBudgetMemory": 100,
      "cekForceCost-exBudgetCPU": 23000,
      "cekForceCost-exBudgetMemory": 100,
      "cekLamCost-exBudgetCPU": 23000,
      "cekLamCost-exBudgetMemory": 100,
      "cekStartupCost-exBudgetCPU": 100,
      "cekStartupCost-exBudgetMemory": 100,
      "cekVarCost-exBudgetCPU": 23000,
      "cekVarCost-exBudgetMemory": 100,
      "chooseData-cpu-arguments": 19537,
      "chooseData-memory-arguments": 32,
      "chooseList-cpu-arguments": 175354,
      "chooseList-memory-arguments": 32,
      "chooseUnit-cpu-arguments": 46417,
      "chooseUnit-memory-arguments": 4,
      "consByteString-cpu-arguments-intercept": 221973,
      "consByteString-cpu-arguments-slope": 511,
      "consByteString-memory-arguments-intercept": 0,
      "consByteString-memory-arguments-slope": 1,
      "constrData-cpu-arguments": 89141,
      "constrData-memory-arguments": 32,
      "decodeUtf8-cpu-arguments-intercept": 497525,
      "decodeUtf8-cpu-arguments-slope": 14068,
      "decodeUtf8-memory-arguments-intercept": 4,
      "decodeUtf8-memory-arguments-slope": 2,
      "divideInteger-cpu-arguments-constant": 196500,
      "divideInteger-cpu-arguments-model-arguments-intercept": 453240,
      "divideInteger-cpu-arguments-model-arguments-slope": 220,
      "divideInteger-memory-arguments-intercept": 0,
      "divideInteger-memory-arguments-minimum": 1,
      "divideInteger-memory-arguments-slope": 1,
      "encodeUtf8-cpu-arguments-intercept": 1000,
      "encodeUtf8-cpu-arguments-slope": 28662,
      "encodeUtf8-memory-arguments-intercept": 4,
      "encodeUtf8-memory-arguments-slope": 2,
      "equalsByteString-cpu-arguments-constant": 245000,
      "equalsByteString-cpu-arguments-intercept": 216773,
      "equalsByteString-cpu-arguments-slope": 62,
      "equalsByteString-memory-arguments": 1,
      "equalsData-cpu-arguments-intercept": 1060367,
      "equalsData-cpu-arguments-slope": 12586,
      "equalsData-memory-arguments": 1,
      "equalsInteger-cpu-arguments-intercept": 208512,
      "equalsInteger-cpu-arguments-slope": 421,
      "equalsInteger-memory-arguments": 1,
      "equalsString-cpu-arguments-constant": 187000,
      "equalsString-cpu-arguments-intercept": 1000,
      "equalsString-cpu-arguments-slope": 52998,
      "equalsString-memory-arguments": 1,
      "fstPair-cpu-arguments": 80436,
      "fstPair-memory-arguments": 32,
      "headList-cpu-arguments": 43249,
      "headList-memory-arguments": 32,
      "iData-cpu-arguments": 1000,
      "iData-memory-arguments": 32,
      "ifThenElse-cpu-arguments": 80556,
      "ifThenElse-memory-arguments": 1,
      "indexByteString-cpu-arguments": 57667,
      "indexByteString-memory-arguments": 4,
      "lengthOfByteString-cpu-arguments": 1000,
      "lengthOfByteString-memory-arguments": 10,
      "lessThanByteString-cpu-arguments-intercept": 197145,
      "lessThanByteString-cpu-arguments-slope": 156,
      "lessThanByteString-memory-arguments": 1,
      "lessThanEqualsByteString-cpu-arguments-intercept": 197145,
      "lessThanEqualsByteString-cpu-arguments-slope": 156,
      "lessThanEqualsByteString-memory-arguments": 1,
      "lessThanEqualsInteger-cpu-arguments-intercept": 204924,
      "lessThanEqualsInteger-cpu-arguments-slope": 473,
      "lessThanEqualsInteger-memory-arguments": 1,
      "lessThanInteger-cpu-arguments-intercept": 208896,
      "lessThanInteger-cpu-arguments-slope": 511,
      "lessThanInteger-memory-arguments": 1,
      "listData-cpu-arguments": 52467,
      "listData-memory-arguments": 32,
      "mapData-cpu-arguments": 64832,
      "mapData-memory-arguments": 32,
      "mkCons-cpu-arguments": 65493,
      "mkCons-memory-arguments": 32,
      "mkNilData-cpu-arguments": 22558,
      "mkNilData-memory-arguments": 32,
      "mkNilPairData-cpu-arguments": 16563,
      "mkNilPairData-memory-arguments": 32,
      "mkPairData-cpu-arguments": 76511,
      "mkPairData-memory-arguments": 32,
      "modInteger-cpu-arguments-constant": 196500,
      "modInteger-cpu-arguments-model-arguments-intercept": 453240,
      "modInteger-cpu-arguments-model-arguments-slope": 220,
      "modInteger-memory-arguments-intercept": 0,
      "modInteger-memory-arguments-minimum": 1,
      "modInteger-memory-arguments-slope": 1,
      "multiplyInteger-cpu-arguments-intercept": 69522,
      "multiplyInteger-cpu-arguments-slope": 11687,
      "multiplyInteger-memory-arguments-intercept": 0,
      "multiplyInteger-memory-arguments-slope": 1,
      "nullList-cpu-arguments": 60091,
      "nullList-memory-arguments": 32,
      "quotientInteger-cpu-arguments-constant": 196500,
      "quotientInteger-cpu-arguments-model-arguments-intercept": 453240,
      "quotientInteger-cpu-arguments-model-arguments-slope": 220,
      "quotientInteger-memory-arguments-intercept": 0,
      "quotientInteger-memory-arguments-minimum": 1,
      "quotientInteger-memory-arguments-slope": 1,
      "remainderInteger-cpu-arguments-constant": 196500,
      "remainderInteger-cpu-arguments-model-arguments-intercept": 453240,
      "remainderInteger-cpu-arguments-model-arguments-slope": 220,
      "remainderInteger-memory-arguments-intercept": 0,
      "remainderInteger-memory-arguments-minimum": 1,
      "remainderInteger-memory-arguments-slope": 1,
      "serialiseData-cpu-arguments-intercept": 1159724,
      "serialiseData-cpu-arguments-slope": 392670,
      "serialiseData-memory-arguments-intercept": 0,
      "serialiseData-memory-arguments-slope": 2,
      "sha2_256-cpu-arguments-intercept": 806990,
      "sha2_256-cpu-arguments-slope": 30482,
      "sha2_256-memory-arguments": 4,
      "sha3_256-cpu-arguments-intercept": 1927926,
      "sha3_256-cpu-arguments-slope": 82523,
      "sha3_256-memory-arguments": 4,
      "sliceByteString-cpu-arguments-intercept": 265318,
      "sliceByteString-cpu-arguments-slope": 0,
      "sliceByteString-memory-arguments-intercept": 4,
      "sliceByteString-memory-arguments-slope": 0,
      "sndPair-cpu-arguments": 85931,
      "sndPair-memory-arguments": 32,
      "subtractInteger-cpu-arguments-intercept": 205665,
      "subtractInteger-cpu-arguments-slope": 812,
      "subtractInteger-memory-arguments-intercept": 1,
      "subtractInteger-memory-arguments-slope": 1,
      "tailList-cpu-arguments": 41182,
      "tailList-memory-arguments": 32,
      "trace-cpu-arguments": 212342,
      "trace-memory-arguments": 32,
      "unBData-cpu-arguments": 31220,
      "unBData-memory-arguments": 32,
      "unConstrData-cpu-arguments": 32696,
      "unConstrData-memory-arguments": 32,
      "unIData-cpu-arguments": 43357,
      "unIData-memory-arguments": 32,
      "unListData-cpu-arguments": 32247,
      "unListData-memory-arguments": 32,
      "unMapData-cpu-arguments": 38314,
      "unMapData-memory-arguments": 32,
      "verifyEcdsaSecp256k1Signature-cpu-arguments": 35892428,
      "verifyEcdsaSecp256k1Signature-memory-arguments": 10,
      "verifyEd25519Signature-cpu-arguments-intercept": 9462713,
      "verifyEd25519Signature-cpu-arguments-slope": 1021,
      "verifyEd25519Signature-memory-arguments": 10,
      "verifySchnorrSecp256k1Signature-cpu-arguments-intercept": 38887044,
      "verifySchnorrSecp256k1Signature-cpu-arguments-slope": 32947,
      "verifySchnorrSecp256k1Signature-memory-arguments": 10
    },
    "PlutusV3": {
      "0": 0,
      "1": 0,
      "2": 0,
      "3": 0,
      "4": 0,
      "5": 0,
      "6": 0,
      "7": 0,
      "8": 0,
      "9": 0,
      "10": 0,
      "11": 0,
      "12": 0,
      "13": 0,
      "14": 0,
      "15": 0,
      "16": 0,
      "17": 0,
      "18": 0,
      "19": 0,
      "20": 0,
      "21": 0,
      "22": 0,
      "23": 0,
      "24": 0,
      "25": 0,
      "26": 0,
      "27": 0,
      "28": 0,
      "29": 0,
      "30": 0,
      "31": 0,
      "32": 0,
      "33": 0,
      "34": 0,
      "35": 0,
      "36": 0,
      "37": 0,
      "38": 0,
      "39": 0,
      "40": 0,
      "41": 0,
      "42": 0,
      "43": 0,
      "44": 0,
      "45": 0,
      "46": 0,
      "47": 0,
      "48": 0,
      "49": 0,
      "50": 0,
      "51": 0,
      "52": 0,
      "53": 0,
      "54": 0,
      "55": 0,
      "56": 0,
      "57": 0,
      "58": 0,
      "59": 0,
      "60": 0,
      "61": 0,
      "62": 0,
      "63": 0,
      "64": 0,
      "65": 0,
      "66": 0,
      "67": 0,
      "68": 0,
      "69": 0,
      "70": 0,
      "71": 0,
      "72": 0,
      "73": 0,
      "74": 0,
      "75": 0,
      "76": 0,
      "77": 0,
      "78": 0,
      "79": 0,
      "80": 0,
      "81": 0,
      "82": 0,
      "83": 0,
      "84": 0,
      "85": 0,
      "86": 0,
      "87": 0,
      "88": 0,
      "89": 0,
      "90": 0,
      "91": 0,
      "92": 0,
      "93": 0,
      "94": 0,
      "95": 0,
      "96": 0,
      "97": 0,
      "98": 0,
      "99": 0,
      "100": 0,
      "101": 0,
      "102": 0,
      "103": 0,
      "104": 0,
      "105": 0,
      "106": 0,
      "107": 0,
      "108": 0,
      "109": 0,
      "110": 0,
      "111": 0,
      "112": 0,
      "113": 0,
      "114": 0,
      "115": 0,
      "116": 0,
      "117": 0,
      "118": 0,
      "119": 0,
      "120": 0,
      "121": 0,
      "122": 0,
      "123": 0,
      "124": 0,
      "125": 0,
      "126": 0,
      "127": 0,
      "128": 0,
      "129": 0,
      "130": 0,
      "131": 0,
      "132": 0,
      "133": 0,
      "134": 0,
      "135": 0,
      "136": 0,
      "137": 0,
      "138": 0,
      "139": 0,
      "140": 0,
      "141": 0,
      "142": 0,
      "143": 0,
      "144": 0,
      "145": 0,
      "146": 0,
      "147": 0,
      "148": 0,
      "149": 0,
      "150": 0,
      "151": 0,
      "152": 0,
      "153": 0,
      "154": 0,
      "155": 0,
      "156": 0,
      "157": 0,
      "158": 0,
      "159": 0,
      "160": 0,
      "161": 0,
      "162": 0,
      "163": 0,
      "164": 0,
      "165": 0,
      "166": 0,
      "167": 0,
      "168": 0,
      "169": 0,
      "170": 0,
      "171": 0,
      "172": 0,
      "173": 0,
      "174": 0,
      "175": 0,
      "176": 0,
      "177": 0,
      "178": 0,
      "179": 0,
      "180": 0,
      "181": 0,
      "182": 0,
      "183": 0,
      "184": 0,
      "185": 0,
      "186": 0,
      "187": 0,
      "188": 0,
      "189": 0,
      "190": 0,
      "191": 0,
      "192": 0,
      "193": 0,
      "194": 0,
      "195": 0,
      "196": 0,
      "197": 0,
      "198": 0,
      "199": 0,
      "200": 0,
      "201": 0,
      "202": 0,
      "203": 0,
      "204": 0,
      "205": 0,
      "206": 0,
      "207": 0,
      "208": 0,
      "209": 0,
      "210": 0,
      "211": 0,
      "212": 0,
      "213": 0,
      "214": 0,
      "215": 0,
      "216": 0,
      "217": 0,
      "218": 0,
      "219": 0,
      "220": 0,
      "221": 0,
      "222": 0,
      "223": 0,
      "224": 0,
      "225": 0,
      "226": 0,
      "227": 0,
      "228": 0,
      "229": 0,
      "230": 0,
      "231": 0,
      "232": 0,
      "233": 0,
      "234": 0,
      "235": 0,
      "236": 0,
      "237": 0,
      "238": 0,
      "239": 0,
      "240": 0,
      "241": 0,
      "242": 0,
      "243": 0,
      "244": 0,
      "245": 0,
      "246": 0,
      "247": 0,
      "248": 0,
      "249": 0,
      "250": 0,
      "251": 0,
      "252": 0,
      "253": 0,
      "254": 0,
      "255": 0,
      "256": 0,
      "257": 0,
      "258": 0,
      "259": 0
    }
  },
  "price_mem": 0.0577,
  "price_step": 0.0000721,
  "max_tx_ex_mem": "16000000",
  "max_tx_ex_steps": "10000000000",
  "max_block_ex_mem": "80000000",
  "max_block_ex_steps": "40000000000",
  "max_val_size": "5000",
  "collateral_percent": 150,
  "max_collateral_inputs": 3,
  "coins_per_utxo_size": "4310",
  "coins_per_utxo_word": "4310",
  "pvt_motion_no_confidence": 0.51,
  "pvt_committee_normal": 0.51,
  "pvt_committee_no_confidence": 0.51,
  "pvt_hard_fork_initiation": 0.51,
  "dvt_motion_no_confidence": 0.51,
  "dvt_committee_normal": 0.51,
  "dvt_committee_no_confidence": 0.51,
  "dvt_update_to_constitution": 0.51,
  "dvt_hard_fork_initiation": 0.51,
  "dvt_p_p_network_group": 0.51,
  "dvt_p_p_economic_group": 0.51,
  "dvt_p_p_technical_group": 0.51,
  "dvt_p_p_gov_group": 0.51,
  "dvt_treasury_withdrawal": 0.51,
  "committee_min_size": "0",
  "committee_max_term_length": "200",
  "gov_action_lifetime": "10",
  "gov_action_deposit": "1000000000",
  "drep_deposit": "2000000",
  "drep_activity": "20",
  "pvtpp_security_group": 0.51,
  "min_fee_ref_script_cost_per_byte": 0
}
```
</details>
